---
deployment:
  tasks:
    - export DEPLOYPATH=/home/exmas1037/repositories/master
    - /bin/cp  -R service/. $DEPLOYPATH
    - /bin/cp  -R blueprints/. $DEPLOYPATH
    - /bin/cp  -R __init__.py/. $DEPLOYPATH
    